apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pointscollection
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pointscollection
    spec:
      containers:
      - name: pointscollection
        image: $DOCKER_REGISTRY/$DOCKER_REPO:$WERCKER_GIT_COMMIT
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 500Mi
            cpu: 0.5
          limits:
            memory: 500Mi
            cpu: 0.5
        imagePullPolicy: Always
      imagePullSecrets:
      - name: wrelease
